### ISSUE TITLE
Download command-line tools

### ISSUE THREAD

**Issue by wieslawsoltes** [wieslawsoltes/BatchEncoder#82]
- [x] Specify tool file format
- [x] Configure tools dialog #85
- [x] Download files #85
- [x] Unpack downloaded files #85
- [x] Install downloaded files #85

Configuration file format:
* https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/BatchEncoder.tools

Unpacking downloaded archives:
* https://github.com/rikyoz/bit7z
* https://github.com/getnamo/7zip-cpp
* http://www.7-zip.org/sdk.html
* https://social.msdn.microsoft.com/Forums/vstudio/en-US/45668d18-2840-4887-87e1-4085201f4103/visual-c-to-unzip-a-zip-file-to-a-specific-directory?forum=vclanguage

Downloading files:
* http://www.cplusplus.com/forum/windows/107840/
* https://msdn.microsoft.com/en-us/library/ms775123(v=vs.85).aspx
* http://www.cplusplus.com/forum/windows/108182/
* http://cpp0x.pl/forum/temat/?id=6364

Unpack using 7-zip command-line:
* http://www.7-zip.org/download.html
* http://www.7-zip.org/a/7z1701-extra.7z
* `7za x -y -otools\NeroAACCodec-1.5.4 tools\NeroAACCodec-1.5.4.zip`
* https://github.com/wieslawsoltes/7-Zip

```
Can I use the EXE or DLL files from 7-Zip in a commercial application?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Yes, but you are required to specify in documentation for your application:
  (1) that you used parts of the 7-Zip program, 
  (2) that 7-Zip is licensed under the GNU LGPL license and 
  (3) you must give a link to www.7-zip.org, where the source code can be found.
```

```
7-Zip (a) 17.01 beta (x86) : Copyright (c) 1999-2017 Igor Pavlov : 2017-08-28

Usage: 7za <command> [<switches>...] <archive_name> [<file_names>...]

<Commands>
  a : Add files to archive
  b : Benchmark
  d : Delete files from archive
  e : Extract files from archive (without using directory names)
  h : Calculate hash values for files
  i : Show information about supported formats
  l : List contents of archive
  rn : Rename files in archive
  t : Test integrity of archive
  u : Update files to archive
  x : eXtract files with full paths

<Switches>
  -- : Stop switches parsing
  @listfile : set path to listfile that contains file names
  -ai[r[-|0]]{@listfile|!wildcard} : Include archives
  -ax[r[-|0]]{@listfile|!wildcard} : eXclude archives
  -ao{a|s|t|u} : set Overwrite mode
  -an : disable archive_name field
  -bb[0-3] : set output log level
  -bd : disable progress indicator
  -bs{o|e|p}{0|1|2} : set output stream for output/error/progress line
  -bt : show execution time statistics
  -i[r[-|0]]{@listfile|!wildcard} : Include filenames
  -m{Parameters} : set compression Method
    -mmt[N] : set number of CPU threads
    -mx[N] : set compression level: -mx1 (fastest) ... -mx9 (ultra)
  -o{Directory} : set Output directory
  -p{Password} : set Password
  -r[-|0] : Recurse subdirectories
  -sa{a|e|s} : set Archive name mode
  -scc{UTF-8|WIN|DOS} : set charset for for console input/output
  -scs{UTF-8|UTF-16LE|UTF-16BE|WIN|DOS|{id}} : set charset for list files
  -scrc[CRC32|CRC64|SHA1|SHA256|*] : set hash function for x, e, h commands
  -sdel : delete files after compression
  -seml[.] : send archive by email
  -sfx[{name}] : Create SFX archive
  -si[{name}] : read data from stdin
  -slp : set Large Pages mode
  -slt : show technical information for l (List) command
  -snh : store hard links as links
  -snl : store symbolic links as links
  -sni : store NT security information
  -sns[-] : store NTFS alternate streams
  -so : write data to stdout
  -spd : disable wildcard matching for file names
  -spe : eliminate duplication of root folder for extract command
  -spf : use fully qualified file paths
  -ssc[-] : set sensitive case mode
  -ssw : compress shared files
  -stl : set archive timestamp from the most recently modified file
  -stm{HexMask} : set CPU thread affinity mask (hexadecimal number)
  -stx{Type} : exclude archive type
  -t{Type} : Set type of archive
  -u[-][p#][q#][r#][x#][y#][z#][!newArchiveName] : Update options
  -v{Size}[b|k|m|g] : Create volumes
  -w[{path}] : assign Work directory. Empty path means a temporary directory
  -x[r[-|0]]{@listfile|!wildcard} : eXclude filenames
  -y : assume Yes on all queries
```

**Comment by wieslawsoltes** [comment]
Proposed configuration file format:

`BatchEncoder.tools`

```XML
<?xml version="1.0" encoding="UTF-8"?>
<Tools>
    <Tool name="LAME" platform="x86" formats="FAAC_AAC,LAME_MP3_WAV" url="http://www.rarewares.org/files/mp3/lame3.99.5.zip" file="lame3.99.5.zip" extract="zip" path="tools/lame3.99.5/lame.exe"/>
</Tools>
```

**Comment by wieslawsoltes** [comment]
Unpacking downloaded archives:
* https://social.msdn.microsoft.com/Forums/vstudio/en-US/45668d18-2840-4887-87e1-4085201f4103/visual-c-to-unzip-a-zip-file-to-a-specific-directory?forum=vclanguage
* https://github.com/getnamo/7zip-cpp
* http://www.7-zip.org/sdk.html

**Comment by wieslawsoltes** [comment]
Downloading files:
* https://msdn.microsoft.com/en-us/library/ms775123(v=vs.85).aspx
* http://www.cplusplus.com/forum/windows/108182/
* http://cpp0x.pl/forum/temat/?id=6364

**Comment by wieslawsoltes** [comment]
http://www.7-zip.org/download.html

http://www.7-zip.org/a/7z1701-extra.7z

`7za x -y -o"tools\NeroAACCodec-1.5.4" "tools\NeroAACCodec-1.5.4.zip"`

```
Can I use the EXE or DLL files from 7-Zip in a commercial application?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Yes, but you are required to specify in documentation for your application:
  (1) that you used parts of the 7-Zip program, 
  (2) that 7-Zip is licensed under the GNU LGPL license and 
  (3) you must give a link to www.7-zip.org, where the source code can be found.
```

```
7-Zip (a) 17.01 beta (x86) : Copyright (c) 1999-2017 Igor Pavlov : 2017-08-28

Usage: 7za <command> [<switches>...] <archive_name> [<file_names>...]

<Commands>
  a : Add files to archive
  b : Benchmark
  d : Delete files from archive
  e : Extract files from archive (without using directory names)
  h : Calculate hash values for files
  i : Show information about supported formats
  l : List contents of archive
  rn : Rename files in archive
  t : Test integrity of archive
  u : Update files to archive
  x : eXtract files with full paths

<Switches>
  -- : Stop switches parsing
  @listfile : set path to listfile that contains file names
  -ai[r[-|0]]{@listfile|!wildcard} : Include archives
  -ax[r[-|0]]{@listfile|!wildcard} : eXclude archives
  -ao{a|s|t|u} : set Overwrite mode
  -an : disable archive_name field
  -bb[0-3] : set output log level
  -bd : disable progress indicator
  -bs{o|e|p}{0|1|2} : set output stream for output/error/progress line
  -bt : show execution time statistics
  -i[r[-|0]]{@listfile|!wildcard} : Include filenames
  -m{Parameters} : set compression Method
    -mmt[N] : set number of CPU threads
    -mx[N] : set compression level: -mx1 (fastest) ... -mx9 (ultra)
  -o{Directory} : set Output directory
  -p{Password} : set Password
  -r[-|0] : Recurse subdirectories
  -sa{a|e|s} : set Archive name mode
  -scc{UTF-8|WIN|DOS} : set charset for for console input/output
  -scs{UTF-8|UTF-16LE|UTF-16BE|WIN|DOS|{id}} : set charset for list files
  -scrc[CRC32|CRC64|SHA1|SHA256|*] : set hash function for x, e, h commands
  -sdel : delete files after compression
  -seml[.] : send archive by email
  -sfx[{name}] : Create SFX archive
  -si[{name}] : read data from stdin
  -slp : set Large Pages mode
  -slt : show technical information for l (List) command
  -snh : store hard links as links
  -snl : store symbolic links as links
  -sni : store NT security information
  -sns[-] : store NTFS alternate streams
  -so : write data to stdout
  -spd : disable wildcard matching for file names
  -spe : eliminate duplication of root folder for extract command
  -spf : use fully qualified file paths
  -ssc[-] : set sensitive case mode
  -ssw : compress shared files
  -stl : set archive timestamp from the most recently modified file
  -stm{HexMask} : set CPU thread affinity mask (hexadecimal number)
  -stx{Type} : exclude archive type
  -t{Type} : Set type of archive
  -u[-][p#][q#][r#][x#][y#][z#][!newArchiveName] : Update options
  -v{Size}[b|k|m|g] : Create volumes
  -w[{path}] : assign Work directory. Empty path means a temporary directory
  -x[r[-|0]]{@listfile|!wildcard} : eXclude filenames
  -y : assume Yes on all queries
```

**Comment by wieslawsoltes** [comment]
Proposal to use `$ToolsDirectory$` variable:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<Tool 
     name="lame_x64" 
     platform="x64" 
     formats="LAME_MP3,LAME_MP3_WAV,LAME_MP1_WAV,LAME_MP2_WAV,LAME_MP3_WAV" 
     url="http://www.rarewares.org/files/mp3/lame3.100-64.zip" 
     file="tools\lame3.100-64.zip" 
     extract="7za x -y -otools\lame3.100-64 tools\lame3.100-64.zip" 
     path="lame3.100-64\lame.exe"/>
```

```XML
<Tool 
     name="lame_x64" 
     platform="x64" 
     formats="LAME_MP3,LAME_MP3_WAV,LAME_MP1_WAV,LAME_MP2_WAV,LAME_MP3_WAV" 
     url="http://www.rarewares.org/files/mp3/lame3.100-64.zip" 
     file="$ToolsDirectory$\lame3.100-64.zip" 
     extract="7za x -y -o$ToolsDirectory$\lame3.100-64 $ToolsDirectory$\lame3.100-64.zip" 
     path="$ToolsDirectory$\lame3.100-64\lame.exe"/>
```
